### ISSUE TITLE
Bug with viber package installation via eepm.

### ISSUE THREAD

**Issue by VladimirVolkov** [Etersoft/eepm#10]
OS:
PRETTY_NAME="ALT Workstation K 9.2  (Centaurea Pineticola)"

eepm version:
Name        : eepm
Version     : 3.9.14
Release     : alt1
DistTag     : p9+270514.10.4.1
Architecture: noarch
Install Date: Чт 03 мар 2022 15:38:20
Group       : System/Configuration/Packaging
Size        : 400409
License     : AGPL-3.0+
Signature   : RSA/SHA1, Пт 16 июл 2021 15:50:27, Key ID 2b6b82cb7aed4d09
Source RPM  : eepm-3.9.14-alt1.src.rpm
Build Date  : Пт 16 июл 2021 15:50:24
Build Host  : lav-p9.hasher.altlinux.org
Relocations : (not relocatable)
Packager    : Vitaly Lipatov <lav@altlinux.ru>
Vendor      : ALT Linux Team
URL         : http://wiki.etersoft.ru/EPM

Error message:
Выбрано viber для '/tmp/.private/root/tmp.HSQrPrAYzO/viber-16.1.0.37-alt1.repacked.with.epm.2.x86_64.rpm'

Некоторые пакеты установить невозможно. Это может означать, что Вы
потребовали невозможного, либо пользуетесь нестабильным репозиторием.
Часть необходимых пакетов либо ещё не создана, либо была удалена
из каталога 'Входящие'.

Так как для выполнения Вашего запроса достаточно одной операции, то
скорее всего этот пакет просто невозможно установить. Сообщите, пожалуйста,
об этом как о найденной ошибке в пакете.
Эти сведения могут помочь найти выход из ситуации:

Следующие пакеты имеют неудовлетворенные зависимости:
  viber: Требует: libtiff.so.5(LIBTIFF_4.0)(64bit) но пакет не может быть установлен
E: Извините, `битые' пакеты
rmdir: удаление каталога, '/tmp/.private/root/tmp.iF1WKcimNR'

**Comment by vitlav** [comment]
Исправлено в epm 3.15.*
Обновлённая версия ещё не дошла до репозитория, пока можно обновить только командой
$ epm ei
