### ISSUE TITLE
Не обновлять через epm play --update если установлено из репозитория RED OS

### ISSUE THREAD

**Issue by AlexanderShad** [Etersoft/eepm#165]
Добрый день.

RedOS8

Если пакет установлен из репозитория, то при epm play --update  пытается обновить из интернета, к примеру тот же яндекс браузер или кодиум, что на мой взгляд не правильно, и нужно сделать как на Альт, чтоб он писал, что пакет установлен из репозитория.

Сказать по правде если я правильно понял собака зарыта в epm-status -> epm_status_original()
Я честно поковырял, но у меня так ничего и не вышло )) 
Могу предположить, что  значение $DISTRNAME для RedOS  это RED OS .. хотя я не совсем понял откуда оно тянется... если честно... в любом случае как уже написал у меня не получилось )

Будет интересно потом посмотреть... )

С уважением

**Comment by Boria138** [comment]
> Добрый день.
> 
> RedOS8
> 
> Если пакет установлен из репозитория, то при epm play --update пытается обновить из интернета, к примеру тот же яндекс браузер или кодиум, что на мой взгляд не правильно, и нужно сделать как на Альт, чтоб он писал, что пакет установлен из репозитория.
> 
> Сказать по правде если я правильно понял собака зарыта в epm-status -> epm_status_original() Я честно поковырял, но у меня так ничего и не вышло )) Могу предположить, что значение $DISTRNAME для RedOS это RED OS .. хотя я не совсем понял откуда оно тянется... если честно... в любом случае как уже написал у меня не получилось )
> 
> Будет интересно потом посмотреть... )
> 
> С уважением

Проверь пожалуйста

https://github.com/Etersoft/eepm/pull/169

**Comment by AlexanderShad** [comment]
ОК... в понедельник на работе буду, посмотрю отпишусь

**Comment by Boria138** [comment]
> ОК... в понедельник на работе буду, посмотрю отпишусь

Я сам тоже на RedOS естественно всё проверил прежде чем PR делать, но вдруг я чего упустил

**Comment by AlexanderShad** [comment]
> > ОК... в понедельник на работе буду, посмотрю отпишусь
> 
> Я сам тоже на RedOS естественно всё проверил прежде чем PR делать, но вдруг я чего упустил

Приветствую.

В общем варнинги лишние

alien
Package alien is already installed from repository (use --force to override it).
**WARNING: App alien is not installed**

codium
Package codium is already installed, packaged by vendor redsoft.
**WARNING: App codium is not installed**

А также почему-то проскочил Яндекс браузер
yandex-browser
 $ /usr/bin/env bash /etc/eepm/play.d/yandex-browser.sh --update
 $ epm installed yandex-browser-stable
 $ epm mark checkhold yandex-browser-stable
 $ epm --short --version
 $ eget -q -O- https://eepm.ru/releases/3.62.9/app-versions/yandex-browser-stable
Updating yandex-browser-stable from 24.1.3.847 to 24.4.1.915 version ...
...
Хотя у меня
rpm -qa | grep yandex-browser
yandex-browser-release-2.0-2.red80.noarch
yandex-browser-stable-24.1.3.847-epm1.repacked.2.x86_64

**Comment by Boria138** [comment]
> > > ОК... в понедельник на работе буду, посмотрю отпишусь
> > 
> > Я сам тоже на RedOS естественно всё проверил прежде чем PR делать, но вдруг я чего упустил
> 
> Приветствую.
> 
> Варнинги лишние, остальное ок.
> 
> alien
> Package alien is already installed from repository (use --force to override it).
> **WARNING: App alien is not installed**
> 
> codium
> Package codium is already installed, packaged by vendor redsoft.
> **WARNING: App codium is not installed**
> 

Спасибо, посмотрю откуда Warning и подправлю

**Comment by Boria138** [comment]
Загрузился в alt с оригинальным epm и там такой же warning так что это поведение по умолчанию, не совсем логичное, я бы хотя бы дописал not installed from epm play, или вообще этот warning убрал

**Comment by Boria138** [comment]
@vitlav Можно уберу этот непонятный Warning который вводит в заблуждение?

**Comment by AlexanderShad** [comment]
> Загрузился в alt с оригинальным epm и там такой же warning так что это поведение по умолчанию, не совсем логичное, я бы хотя бы дописал not installed from epm play, или вообще этот warning убрал

Согласен, они не логичные

**Comment by Boria138** [comment]
@vitlav PR относящиеся к этой ошибке вы уже приняли можно закрывать ошибку

**Comment by AlexanderShad** [comment]
@Boria138 в общем на 3.62.13 не работает.
то что установлено с репозитория, тот же кодиум, пытается поставить при обновлении епм плей алл

**Comment by Boria138** [comment]
> @Boria138 в общем на 3.62.13 не работает.
> то что установлено с репозитория, тот же кодиум, пытается поставить при обновлении епм плей алл

Так это только в devel на данный момент по моему

**Comment by AlexanderShad** [comment]
[Запись экрана от 2024-08-13 16-36-48.webm](https://github.com/user-attachments/assets/67675fb0-5751-459e-9c4f-b4744d10eab9)

**Comment by AlexanderShad** [comment]
> > @Boria138 в общем на 3.62.13 не работает.
> > то что установлено с репозитория, тот же кодиум, пытается поставить при обновлении епм плей алл
> 
> Так это только в devel на данный момент по моему

хм.. может я что уже на путал.. голова не соображает под вечер) 
завтра вытащу девел посмотрю
