### ISSUE TITLE
/etc/modprobe.d/blacklist-nvidia-x11.conf в switch-to-nvidia.sh

### ISSUE THREAD

**Issue by vlad196** [Etersoft/eepm#171]
Есть ли смысл в eepm использовать каталог /etc/modprobe.d/ вместо /lib/modprobe.d/ ?
https://github.com/Etersoft/eepm/blob/master/prescription.d/switch-to-nvidia.sh#L61

Мне видеться, что если blacklist-nvidia-x11.conf был бы в /lib/modprobe.d/, то его можно было бы спокойно переназначить в /etc/, без страха, что повторных запуск switch-to-nvidia.sh затрёт твои настройки.

**Comment by Boria138** [comment]
> Есть ли смысл в eepm использовать каталог /etc/modprobe.d/ вместо /lib/modprobe.d/ ? https://github.com/Etersoft/eepm/blob/master/prescription.d/switch-to-nvidia.sh#L61
> 
> Мне видеться, что если blacklist-nvidia-x11.conf был бы в /lib/modprobe.d/, то его можно было бы спокойно переназначить в /etc/, без страха, что повторных запуск switch-to-nvidia.sh затрёт твои настройки.

/lib/modprobe.d это для пакетов epm создаёт пользовательские настройки

**Comment by Boria138** [comment]
Да и повторный запуск ничего не сотрёт необязательно писать именно в blacklist есть например /etc/modprobe/nvidia-common.conf из пакета nvidia_glx_common он при обновлении не затирается
