### ISSUE TITLE
Проблемы с установкой Яндекс Браузера

### ISSUE THREAD

**Issue by X1Z53** [Etersoft/eepm#189]
Я.Браузер Бета не ложится в `/opt` как должна (стабильная версия в `/opt`). Сама эта папка предполагает установку туда сторонних приложений

**Comment by VanoMajukin** [comment]
Не смог воспроизвести, прошу предоставить информацию о системе `epm print info` и текущий список файлов в пакете `epmql yandex-browser-beta `

**Comment by Boria138** [comment]
Тоже не воспроизвелось, похоже какой-то локальный глюк

**Comment by vitlav** [comment]
Никаких подробностей нет.
