### ISSUE TITLE
Не обновлять через epm play --update если установлено из репозитория Fedora

### ISSUE THREAD

**Issue by AlexanderShad** [Etersoft/eepm#200]
Добрый день.

Fedora 40

Если пакет установлен из репозитория, то при epm play --update пытается обновить из интернета, к примеру тот же яндекс браузер или портпротон, что на мой взгляд не правильно, и нужно сделать как на Альт, чтоб он писал, что пакет установлен из репозитория.

С уважением

**Comment by Boria138** [comment]
@AlexanderShad Добавил Fedora, теперь это работает в ALT, Rosa, MOS, RedOS и Fedora

**Comment by AlexanderShad** [comment]
Отлично! будем ждать релиза )
Справедливости ради в 3.62.11 пишет что Unsupported REDOS при epm play --update all

**Comment by AlexanderShad** [comment]
Спасибо
