### ISSUE TITLE
Не работает —update all на REDOS

### ISSUE THREAD

**Issue by AlexanderShad** [Etersoft/eepm#212]
Доброго времени суток
epm 3.62.12-eter1redos
Redos8

При epm full-upgrade не отрабатывает epm play — update all пишет Unsupported RedOs

![IMG_20240724_161251_733.jpg](https://github.com/user-attachments/assets/a4a2f4ce-d8aa-40b0-bd9b-aec6f7c752da)

**Comment by Boria138** [comment]
Если попробовать с devel ветки склонироовать epm и там проверить ? Я буквально недавно RedOS проверял и всё нормально было, хотя я проверял на 7, а не 8, скинь сюда distr_info проверю

**Comment by AlexanderShad** [comment]
ok, в понедельник скину

**Comment by AlexanderShad** [comment]
![IMG_20240729_105327_766_1.jpg](https://github.com/user-attachments/assets/af3a35df-8723-4b36-8b81-06fbb36f6d7f)

**Comment by Boria138** [comment]
@AlexanderShad Вроде ничем не отличается от седьмой версии, на devel ошибка воспроизводится ?

**Comment by AlexanderShad** [comment]
Я скачал девел, закинул из него содержимое play.d .. 
Тоже поведение.
Удалил пакет, удалил руками /etc/epm поставил из репозитория, обновился через epm ei ошибка больше не воспроизвелась.. Что это было, не понял 
Думаю issue можно закрыть.
