### ISSUE TITLE
Unable to repack deb-package with python import gi.repository.GLib - getting "Depends: python3(gi.repository.GLib) (< 0) but it is not installable"

### ISSUE THREAD

**Issue by N0rbert** [Etersoft/eepm#22]
Steps to reproduce:
1. Download needed package by 

       cd ~/Downloads
       wget https://github.com/yuki-iptv/yuki-iptv/releases/download/0.0.4/yuki-iptv_0.0.4_all.deb
 
1. Install necessary dependencies

       apt-get install rpm-build-python rpm-build-python3

1. Try to repack deb-package

       epm install --repack yuki-iptv_0.0.4_all.deb

Expected results:

* package is installed normally.

Actual results:

* package in not installed, last 3 lines in the terminal are the following:

       The following packages have unmet dependencies:
         yuki-iptv: Depends: python3(gi.repository.GLib) (< 0) but it is not installable
       E: Broken packages

   Full log from terminal is attached - see [eepm.log](https://github.com/Etersoft/eepm/files/11241916/eepm.log). 

---

System info: I use ALT Linux Sisyphus with MATE desktop, installed from regular Starterkit ISO and then fully upgraded.

**Comment by vitlav** [comment]
Пакет собран в Сизиф:
https://packages.altlinux.org/ru/sisyphus/srpms/yuki-iptv/

Думаю, установится и в p10.

**Comment by N0rbert** [comment]
Thanks for packaging *yuki-iptv* program!
But the original issue persists even with latest eepm 3.55.8. 
I would suggest to fix it, as this problem may occur with some other different package involving *`python3(gi.repository.GLib)`*.

**Comment by vitlav** [comment]
It is wrong way to add open source program, can be packed natively to the repo, to epm play with repacking some binaries.
But I have improved python3 support in
https://github.com/Etersoft/eepm/commit/dc705563d59bfc8896437f6cbfd114d20d12649b
so the package you requested to repack can be repacked correctly.
