### ISSUE TITLE
Уберите привязку epm ei к бранчам альта

### ISSUE THREAD

**Issue by AlexanderShad** [Etersoft/eepm#228]
Добрый день

Прошу убрать из epm ei привязку к бранчам Альта, так как это не справедливо и грустно.

То есть на РедОС я к примеру могу по epm ei загрузить самую последнюю версию epm и использовать ее, даже если в репозитории старая версия, а на альте нельзя. 

Мол на Р11 делаешь epm ei и он начинает обновление с репозитория... где версия на порядок старее.. и говорит мол нечего обновлять .. 3.62.9 последняя...  ну глупость право..

Без обид, но мне кажется epm ei должен тянуть последнюю версия как он это делает на всех системах, под которые он есть, а не так...  пользователи альта получаются неудел

Обидно

**Comment by AlexanderShad** [comment]
так тоже не работает
$ sudo curl -sL https://eepm.ru/epm.sh | bash /dev/stdin ei
[sudo] password for shad:
 $ eget --check-url https://updates.etersoft.ru/pub/Korinf/x86_64/alt/p11
ERROR: Can't get package url by eepm  (you can discuss the epm 3.62.13 problem in Telegram: https://t.me/useepm)

**Comment by Boria138** [comment]
> так тоже не работает $ sudo curl -sL https://eepm.ru/epm.sh | bash /dev/stdin ei [sudo] password for shad: $ eget --check-url https://updates.etersoft.ru/pub/Korinf/x86_64/alt/p11 ERROR: Can't get package url by eepm (you can discuss the epm 3.62.13 problem in Telegram: https://t.me/useepm)

Под p11 просто нет директории на сервере, похоже ещё не собрано, на p10 он поставит именно самую новую, так что ошибки по сути нет, просто до p11 новая версия ещё не доехала

**Comment by AlexanderShad** [comment]
OK, я понял. 
Подождём 😁
Как заработает, закрою issue )

**Comment by AlexanderShad** [comment]
Почитал переписку в баге, вопрос снят.
Но со своей стороны считаю это несусветной глупостью.
Теперь мне понятно скорее всего причина такого отношения к тому же flatpak и bwrap
