### ISSUE TITLE
Отвязать в epm play yandex-browser аудио кодеки от репозитория Альт

### ISSUE THREAD

**Issue by AlexanderShad** [Etersoft/eepm#232]
Добрый день.

Прошу Вас отвязать аудиокодеки при установке Яндекс браузера через epm play от пакета ffmpeg-plugin-browser из репозитория Альт линукс. Если это возможно.

Для примера в Росе из репозитория устанавливается доп пакет gstreamer1.0-faad

Данная просьба обусловлена очень непонятным, лично мне, отношением/решением ядекса

https://bugzilla.altlinux.org/51210
https://bugzilla.altlinux.org/51217

В одной баге как раз про звук, а другая бага рассказывает почему яндекс браузер из репозитория становится не юзабельным для дома лично для меня, к сожалению

**Comment by AlexanderShad** [comment]
В данный момент, для домашнего использования Яндекс Браузера, со всеми фишками, как по мне, остается как раз решение установки его через epm play... но тут могут быть проблемы со звуком местами.. по этому и написал данный issue

**Comment by Boria138** [comment]
В бета версии браузера кодеки работает нормально, да и нет никаких гарантий что сторонние кодеки так же не будут периодически отваливатся, так что не вижу смысла в отвязке в альте от пакета иэ репозиториев

**Comment by vitlav** [comment]
Мы можем убрать зависимость у пакета (если она есть), чтобы можно быть проверить, что действительно с удалением мешающего пакета становится лучше.
