### ISSUE TITLE
epm play meridius - не работает отправка смс при авторизации

### ISSUE THREAD

**Issue by AlexanderShad** [Etersoft/eepm#240]
Добра.

После установке через epm play и попытке входа не работает отправка смс при двухфакторке

Пишу сюда, потому что Flatpak версия все ок, только после сборки epm play не работает

issue у апстрим закрыл

https://github.com/PurpleHorrorRus/Meridius/issues/66

**Comment by Boria138** [comment]
Через --force ставится 3.1.3 вместо 3.1.0, там код приходит

**Comment by Boria138** [comment]
Вообще в epm 3.64.0 есть --latest вместо --force, но он почему-то не работат, так что пока --force

**Comment by Boria138** [comment]
А --latest должно быть до

./epm play --latest meridius

Сам писал, сам забыл как это работает

**Comment by AlexanderShad** [comment]
Понял принял. Спасибо
