### ISSUE TITLE
flatpak Яндекс браузер не видит vdhcoapp

### ISSUE THREAD

**Issue by AlexanderShad** [Etersoft/eepm#254]
Добрый день.

При установке Яндекс Браузера из flatpak и установке epmp vdhcoapp я браузер не видит плагин.

С flatpak FireFox все нормально, плагин видет

Посмотрите пожалуйста

С уважением

**Comment by Boria138** [comment]
А, может Яндекс браузеру из flatpak просто разрешений не хватило, раз уж с Firefox всё нормально ?

**Comment by Boria138** [comment]
Это вполне может быть проблема браузера из flatpak, проверяется в принципе легко, ставишь дистрибутив где vdhcoapp есть нативный, допустим в ауре в арче есть, и посмотреть как он будет себя вести

**Comment by AlexanderShad** [comment]
> А, может Яндекс браузеру из flatpak просто разрешений не хватило, раз уж с Firefox всё нормально ?

Ну с яндекс браузером было и до этого все грустно, без флетпак. 
Мне кажется это проблема самого яндекс барузера из флетпак. 

Учитвая, что наверное не критично, думаю можно закрыть issue
