### ISSUE TITLE
epmp teamspeak3 - не работает

### ISSUE THREAD

**Issue by AlexanderShad** [Etersoft/eepm#255]
Добрый день.

epmp teamspeak3  - не работает

ERROR: Can't download https://files.teamspeak-services.com/releases/client/3/TeamSpeak3-Client-linux_amd64-3.run 

на оф сайте последняя версия 3,6,2

epmp teamspeak3=3.6.2 - работает

**Comment by Boria138** [comment]
Прошу проверить этот PR

https://github.com/Etersoft/eepm/pull/275

Но, с --force

**Comment by AlexanderShad** [comment]
на Fedora с epm 3.64.0 - не работает

![Снимок экрана_20241110_222439](https://github.com/user-attachments/assets/aae52562-f506-48ef-b6a7-920fedc24e7a)
![Снимок экрана_20241110_222641](https://github.com/user-attachments/assets/7b773bf5-6118-45cd-a039-d9f99df1136c)


на альте наверное работает, поставлю обратно альт, проверю, если работает, закрою issue

**Comment by AlexanderShad** [comment]
На альт линукс работает
