### ISSUE TITLE
WPS Office - Недоступна система скинов

### ISSUE THREAD

**Issue by Ampernic** [Etersoft/eepm#266]
От пользователей Alt Gnome Regular в чат поступила [жалоба](https://t.me/alt_gnome_chat/152295) на систему скинов WPS Office.
Не открывается меню выбора скина.

![Снимок экрана от 2024-10-29 22-15-40](https://github.com/user-attachments/assets/a8b07367-4f26-4b8f-9191-56211e32830a)
![Снимок экрана от 2024-10-29 22-16-49](https://github.com/user-attachments/assets/545a4abb-5ad1-4436-be9f-ebdb51658186)

Проверил на своей машине, поведение подтвердилось. (`wps-office-11.1.0.11723.XA-epm1.repacked.2.x86_64.rpm`)

https://github.com/user-attachments/assets/2a7b9afb-62c1-479b-a8e0-18c100955a71

**Comment by Boria138** [comment]
На Ximper воспроизвет не удалось скины открываются, хоть и достаточно долго (секунд пять) хотелось бы каких нибудь логов запуска или подобного

**Comment by Ampernic** [comment]
> хотелось бы каких нибудь логов запуска или подобного

Мне бы тоже очень хотелось, но он ничего не логирует...

![image](https://github.com/user-attachments/assets/85b17700-264d-419f-8f65-374e3fb8fc5b)

**Comment by Boria138** [comment]
> > хотелось бы каких нибудь логов запуска или подобного
> 
> Мне бы тоже очень хотелось, но он ничего не логирует...
> 
> ![image](https://github.com/user-attachments/assets/85b17700-264d-419f-8f65-374e3fb8fc5b)
> 

В итоге удалось воспроизвести на KDE Regular (на Ximper и WSK всё нормально), попробую отловить баг

**Comment by Boria138** [comment]
Проверил на Fedora 41 с их официальным rpm пакетом, там система скинов так же не работает, делаю вывод что это ошибка аппстрима

**Comment by Boria138** [comment]
@Ampernic Прошу проверить этот PR, вроде тепперь всё работает https://github.com/Etersoft/eepm/pull/270

**Comment by Ampernic** [comment]
> @Ampernic Прошу проверить этот PR, вроде теперь всё работает #270

Подтверждаю, все заработало 
![image](https://github.com/user-attachments/assets/d338ffc3-eee0-479d-a65e-96cae3f2fe07)

**Comment by Ampernic** [comment]
После принятия ПР и обновления в сизифе уберу предупреждение в статье на вики

**Comment by Boria138** [comment]
> уберу предупреждение в статье на вики

Можно добавить этот фикс

rm /opt/kingsoft/wps-office/office6/libstdc++.so*

В PR ещё python2 на python3 заменяется, но это на скины не влияет, мешают запуску именно opt/kingsoft/wps-office/office6/libstdc++.so*
