### ISSUE TITLE
`epm play arduino-ide` - 10890 Неверный системный вызов

### ISSUE THREAD

**Issue by Ampernic** [Etersoft/eepm#295]
Лог установки
```shell
ampernic@alt-tecno ~ $ epm play arduino-ide > play-arduino-ide.log                         1 [21:33:17]
 $ /usr/bin/env bash /etc/eepm/play.d/arduino-ide.sh --run 
 $ epm --short --version
 $ eget -q -O- https://eepm.ru/releases/3.64/app-versions/arduino-ide
 $ eget --list --latest https://github.com/arduino/arduino-ide/releases arduino-ide_2.3.3_Linux_64bit.AppImage
 $ epm install --repack https://github.com/arduino/arduino-ide/releases/download/2.3.3/arduino-ide_2.3.3_Linux_64bit.AppImage
 $ eget --latest https://github.com/arduino/arduino-ide/releases/download/2.3.3/arduino-ide_2.3.3_Linux_64bit.AppImage
 $ /bin/wget --tries 1 --content-disposition https://github.com/arduino/arduino-ide/releases/download/2.3.3/arduino-ide_2.3.3_Linux_64bit.AppImage
--2024-11-22 21:33:43--  https://github.com/arduino/arduino-ide/releases/download/2.3.3/arduino-ide_2.3.3_Linux_64bit.AppImage
Resolving github.com (github.com)... /usr/share/eepm/tools_eget: строка 146: 10890 Неверный системный вызов                      "$@"
WARNING: Failed to download https://github.com/arduino/arduino-ide/releases/download/2.3.3/arduino-ide_2.3.3_Linux_64bit.AppImage, ignoring
ERROR: There was some error during install the application.  (you can discuss the epm 3.64.0-alt1 problem in Telegram: https://t.me/useepm
```

epm print info

```
epm print info                                               [21:41:01]
distro_info v20230406 (EPM version 3.64.0-alt1) : Copyright © 2007-2024 Etersoft

                       Pretty name (--pretty): ALT Regular (20240122) (Sisyphus)
           (--distro-name / --distro-version): Sisyphus / 20240122 (orig. Sisyphus 20240122)
         Base distro name (-d) / version (-v): ALTLinux/Sisyphus
     Vendor distro name (-s) / Repo name (-r): alt / Sisyphus
                 Package manager/type (-g/-p): apt-rpm / rpm
            Base OS name (-o) / CPU arch (-a): linux x86_64
                 CPU norm register size  (-b): 64 bit
                          Virtualization (-i): (host system)
                        CPU Cores/MHz (-c/-z): 16 / 1707 MHz
                      System memory size (-m): 15384 MiB
                 Running service manager (-y): systemd
            Bug report URL (--bug-report-url): https://bugs.altlinux.org/

(run with -h to get help)
```

**Comment by vitlav** [comment]
Покажите, пожалуйста, вывод
epm policy wget

**Comment by Ampernic** [comment]
> Покажите, пожалуйста, вывод epm policy wget

ampernic@alt-tecno ~ $ epm policy wget                                                       [17:52:09]
 $ apt-cache policy wget
wget:
  Установлен: 1.25.0-alt1:sisyphus+362379.100.1.1@1731425502
  Кандидат: 1.25.0-alt1:sisyphus+362379.100.1.1@1731425502
  Таблица версий:
 *** 1.25.0-alt1:sisyphus+362379.100.1.1@1731425502 0
        500 http://ftp.altlinux.org Sisyphus/x86_64/classic pkglist
        100 RPM Database

**Comment by vitlav** [comment]
> > Покажите, пожалуйста, вывод epm policy wget
> 
> ```shell
> ampernic@alt-tecno ~ $ epm policy wget                                                       [17:52:09]
>  $ apt-cache policy wget
> wget:
>   Установлен: 1.25.0-alt1:sisyphus+362379.100.1.1@1731425502
>   Кандидат: 1.25.0-alt1:sisyphus+362379.100.1.1@1731425502
>   Таблица версий:
>  *** 1.25.0-alt1:sisyphus+362379.100.1.1@1731425502 0
>         500 http://ftp.altlinux.org Sisyphus/x86_64/classic pkglist
>         100 RPM Database
> ```
> 
> Немного интересно зачем, остальные play исполняются нормально

Каким-то образом у вас падает wget, хотя эту проблему уже не раз решали, в частности,

https://bugzilla.altlinux.ru/51563

Через что скачивают остальные play, тоже wget? Тогда давайте попробуем отдельно выполнить
wget https://github.com/arduino/arduino-ide/releases/download/2.3.3/arduino-ide_2.3.3_Linux_64bit.AppImage

По следам предыдущих проблем с wget, сможете показать содержимое /etc/resolv.conf ?

**Comment by Ampernic** [comment]
> > > Покажите, пожалуйста, вывод epm policy wget
> > 
> > 
> > ```shell
> > ampernic@alt-tecno ~ $ epm policy wget                                                       [17:52:09]
> >  $ apt-cache policy wget
> > wget:
> >   Установлен: 1.25.0-alt1:sisyphus+362379.100.1.1@1731425502
> >   Кандидат: 1.25.0-alt1:sisyphus+362379.100.1.1@1731425502
> >   Таблица версий:
> >  *** 1.25.0-alt1:sisyphus+362379.100.1.1@1731425502 0
> >         500 http://ftp.altlinux.org Sisyphus/x86_64/classic pkglist
> >         100 RPM Database
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Немного интересно зачем, остальные play исполняются нормально
> 
> Каким-то образом у вас падает wget, хотя эту проблему уже не раз решали, в частности,
> 
> https://bugzilla.altlinux.ru/51563
> 
> Через что скачивают остальные play, тоже wget? Тогда давайте попробуем отдельно выполнить wget https://github.com/arduino/arduino-ide/releases/download/2.3.3/arduino-ide_2.3.3_Linux_64bit.AppImage
> 
> По следам предыдущих проблем с wget, сможете показать содержимое /etc/resolv.conf ?

Очень странно, но теперь ошибка не прявляется вообще...
Было несколько обновлений системы за 4 дня, возможно что-то было затронуто, что могло вызывать.

Но это очень странно, ведь wget обновлялся последний раз 12 числа, и то с фиксом CVE, и я не понимаю, что могло послужить проблемой.

Настройки сети те же, машина та же, были только несколько обновлений... Вынужден извиниться и закрыть ишью за отсутвием воспроизведения.
