### ISSUE TITLE
Обновить версию приложения VK Messenger с версии 5.3.2 ->  6.0.32-117

### ISSUE THREAD

**Issue by OlegShchavelev** [Etersoft/eepm#50]
Большая просьба обновить приложение VK Messenger с версии 5.3.2 ->  6.0.32-117.

Предлагаю изменить установочное задание, а именно инструкцию установочного задание скачивание пакета перед упаковкой:

https://upload.object2.vk-apps.com/vk-me-desktop-dev-5837a06d-5f28-484a-ac22-045903cb1b1a/latest/vk-messenger.deb
https://upload.object2.vk-apps.com/vk-me-desktop-dev-5837a06d-5f28-484a-ac22-045903cb1b1a/latest/vk-messenger.rpm

На текущий момент ссылка:
https://desktop.userapi.com/rpm/master/vk-5.3.2.x86_64.rpm

**Comment by vitlav** [comment]
Исправлено в eepm 3.60.8:
`epm play vk-messenger`
