### ISSUE TITLE
установка vdhcoapp через epmp

### ISSUE THREAD

**Issue by AlexanderShad** [Etersoft/eepm#57]
Доброго времени суток.

В настоящее время наблюдается, что epmp vdhcoapp ставит не рабочую версию компаньона Video DownloadHelper + она идет без ffmpeg

Фактически почему-то не отрабатывает vdhcoapp install , вывод делаю из расчета того, что в NativeMessagingHosts от Google Chrome не падет net.downloadhelper.coapp.json ну и по самому vdhcoapp install ничего не происходит, даже если была поменяна процедура установки в гугле пусто

При попытке, в последствии, поставить принудительно точно рабочую версию 2.0.10

epm play vdhcoapp=2.0.10

наблюдается конфликт версий net.downloadhelper.coapp так как пытается установиться более старая версия.
Удалить пакет более новой версии невозможно, так как его нет... где-то записано, что ставилось, где не искал.

Также, учитывая, что разработчиком не поддерживается Яндекс.Браузер, насколько я понимаю, точнее при динамическим получении информации об установленных браузерах, он его не видит (если  я правильно понял код), предлагаю рассмотреть возможность в vdhcoapp.sh дописать создание net.downloadhelper.coapp.json в конце

echo -e '{\n"type": "stdio",\n"allowed_origins": [\n"chrome-extension://lmjnegcaeklhafolokijcfjliaokphfk/",\n"chrome-extension://pfoiagbblcbmognbkekfpodpidedkmcc/",\n"chrome-extension://jmkaglaafmhbcpleggkmaliipiilhldn/",\n"chrome-extension://fojefjolbhfidomcaelhceoldmmpcaga/"\n],\n  "name": "net.downloadhelper.coapp",\n"description": "Video DownloadHelper companion app",\n"path": "/opt/vdhcoapp/vdhcoapp"\n}' >> $HOME/.config/yandex-browser/NativeMessagingHosts/net.downloadhelper.coapp.json

**Comment by vitlav** [comment]
> Фактически почему-то не отрабатывает vdhcoapp install 
` vdhcoapp install --system` не выполняется намеренно. Вместо этого создаются файлы в пакете
/usr/lib64/mozilla/native-messaging-hosts/net.downloadhelper.coapp.json
/etc/chromium/native-messaging-hosts/net.downloadhelper.coapp.json

Какой другой системный файл может использоваться для Yandex-браузера, не знаю.

**Comment by vitlav** [comment]
Установка обновлена в epm 3.60.9
