### ISSUE TITLE
Ошибка установки teamspeak3 

### ISSUE THREAD

**Issue by AlexanderShad** [Etersoft/eepm#64]
Добрый день. 

Стенд 
OS: ALT Regular Sisyphus x86_64
Kernel: 6.6.18-un-def-alt1
DE: GNOME 45.4 
CPU: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (8) @ 2.100GHz
GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series

eepm-3.60.7-alt1.noarch

Во время установки 

```shell
epm play teamspeak3
```

Выходит критическая ошибка установки teamspeak3 из-за отсутствующей зависимости libwebp.so.6

Пакет libwebp6 удален с Сизиф

**Comment by vitlav** [comment]
Исправлено в eepm 3.60.8
