### ISSUE TITLE
epm play не обновляет программы

### ISSUE THREAD

**Issue by Anexya** [Etersoft/eepm#65]
При использовании epm full-upgrade и отдельно тоже команда epm play --update all не обновляет установленные приложения.
Помогает epm play --update all --force --auto . 
Предварительно сделано epm ei
Система  
epm print info
distro_info v20230406 (EPM version 3.60.7-alt1) : Copyright © 2007-2024 Etersoft

                       Pretty name (--pretty): Ximper Linux 0.9.1 (Alice) (Sisyphus)
           (--distro-name / --distro-version): Etersoft Ximper / 0.9.1 (orig. Etersoft Ximper 0.9)
         Base distro name (-d) / version (-v): ALTLinux/Sisyphus
     Vendor distro name (-s) / Repo name (-r): alt / Sisyphus
                 Package manager/type (-g/-p): apt-rpm / rpm
            Base OS name (-o) / CPU arch (-a): linux x86_64
                 CPU norm register size  (-b): 64 bit
                          Virtualization (-i): (host system)
                        CPU Cores/MHz (-c/-z): 16 / 4416 MHz
                      System memory size (-m): 31498 MiB
                 Running service manager (-y): systemd
            Bug report URL (--bug-report-url): https://bugs.altlinux.org/

**Comment by vitlav** [comment]
Исправлено для epm 3.6.10. Проблема связана с сервером обновлений, сам epm тут не задействован.
