### ISSUE TITLE
epm play: add firestorm, firestorm-os

### ISSUE THREAD

**Issue by drivezt** [Etersoft/eepm#97]
Firestorm Viewer for Second Life:
https://downloads.firestormviewer.org/release/linux/Phoenix-Firestorm-Releasex64-6-6-17-70368.tar.xz

Firestorm Viewer for Open Simulator:
https://downloads.firestormviewer.org/release/linux/Phoenix-FirestormOS-Releasex64-6-6-17-70368.tar.xz

Как пример, в Arch Linux AUR есть пакет firestorm-bin:
https://aur.archlinux.org/packages/firestorm-bin

**Comment by Boria138** [comment]
Добавил, осталось дождаться когда попадёт в релиз

**Comment by vitlav** [comment]
* Вс июн 23 2024 Vitaly Lipatov <lav@altlinux.ru> 3.62.10-alt1
...
- epm play: add cups-drivers-katusham247 (eterbug #17332)
- epm play: add Firestorm Viewer for Open Simulator (eterbug #17325)
- epm play: add Firestorm Viewer for Second Life (eterbug #17325)
